### PR TITLE
REP 4

### PR DESCRIPTION
**Pull request by eckelj**
This is a draft PR to implement Trust Anchor Requirements with the community.

### CODE REVIEW

**Comment by christian-dienbauer** [comment]
@eckelj Nice and concise description. 

Following point I would change:

- For my understanding: A Trust Anchor is “only” a secure element connected to a microcontroller that provides an interface to communicate with the secure element and perform crypto operations. A Trust Anchor does not contain the business logic. A HW-03 (Trusted Gateway), contains or is associated with a Trust Anchor.  I’d rename Trust Anchor with HW-03.

And questions to the CID resolver:

1. Does this need to be an API service to get the URL to the location of the data?
2. If the meta data for all machines is stored in the same place, e.g. on IPFS, couldn’t we just add the URL to the meta data there?
3. If we don’t store the meta data of a machine in the same place, how does one that creates a pop challenge know the URL of the CID-Resolver? Or is there only one CID resolver for the whole network?

**Comment by eckelj** [comment]
@dieni, you consider the Trust Anchor to contain only a secure element and perform HD derivations. That's just a part of what a Trust Anchor does. The Trust Anchor also hosts a Liquid Node and needs to perform data and storage management (as stated in the document). 

How do you want to name this machine/operator-specific logic to avoid calling it business logic?!

@1 CID-resolver does not have to be an API service but can
@2 in theory, yes, but we do not assume that all users will host their data on the same location service or the same platform.
@3 at this point, there is one CID-resolver. This can be decentralized in the future, but it isn't right now. The purpose of the CID-resolver is to decouple the storage of data/metadata in such a way that every organization/user can define the way they want to handle their data.

@dieni I suggest documenting the CID resolver in an explicit REP. how do you feel about this?

**Comment by christian-dienbauer** [comment]
@eckelj check out the component diagram for my understanding of a Trust Anchor. Its just an ESP32 and from what I have heard not intended to run a liquid node. I think we mix terminology. 
Component Diagram App uses data storage via RDDL network

... The diagram shows what we intend to do for MyPower. I'd love to get your feedback on this during a meeting. I'll send you an invite.

CID resolver
- At the moment my understanding is that there are two kind of machine data: 1. meta data of a machine (describes the machine and its environment), 2. time series data (data that was created over time by the machine).
- While the machine owner should define where to store time series data. Is this also necessary for meta data?)
- And as IPFS is already a decentralized CID resolver, why not use this one to store the meta data including the information how to get the URL of the data storage that contains the time series data?

**Comment by eckelj** [comment]
@dieni, I see where the confusion is coming from. Please rename the **_HW-03_** in your graphic with _**Trust Anchor**_. The Secure Element is not the Trust Anchor. 


Strictly speaking: if a CID is referenced via a transaction (e.g. in the data or metadata field) and the transaction is challenged, you have to prove the integrity of all the CIDs ( this should answer your questions 1&2. 

@3: your proposed solution doesn't fix the root cause of data storage delegation. It would only introduce another layer of CID -> CID resolution and thereby obfuscate the process. Feel free to convince me with a potential sequence diagram and the data types in each location. 


Personal note: can you number your questions in the future so I can explicitly reference them and reduce potential misunderstandings?

**Comment by eckelj** [comment]
@dieni I also suggest the following changes:

1. IPFS addressed via the storage connector from 0x21e8
2. Planetmint is connected via the planetmint connector (DLT connector) from 0x21e8
3. liquid is connected via the local liquid node (DLT Connector) on the Trust Anchor (HW-03) from 0x21e8

This is an essential difference, as RDDL expects that the Trust Anchor interacts independently with DLTs.

**Comment by eckelj** [comment]
@dieni you were right about the naming of HW-03 and the Trust Anchors. I adjusted this in the document.

**Review by Cybnon — APPROVED** [review]
Looks good to me also, the grade of details is sufficient I would say

**Pull request merged**
